package main

import (
	"flag"

	config "github.com/ilhamfi27/ddd-golang-template/internal/config/app"
	"github.com/ilhamfi27/ddd-golang-template/internal/handlers"
	_ "github.com/ilhamfi27/ddd-golang-template/swagger" // swagger is generated by Swag CLI, you have to import it.
)

// @title		Example
// @version		1.0.0
// @description		This is a simple API Example.
// @contact.name	Ilham
// @contact.url		https://nashul.com
// @contact.email	support@nashul.com
// @license.name	Apache 2.0
// @license.url		http://www.apache.org/licenses/LICENSE-2.0.html
func main() {
	// Load the environment variables
	config.LoadEnv()

	// Define the --migrate flag as a boolean
	migrate := flag.Bool("migrate", false, "Run database migrations")

	// Parse the command-line flags
	flag.Parse()

	h := handlers.NewHandler()

	if *migrate {
		h.Migrate()
	} else {
		h.Start()
	}
}
