package main

import (
	"context"
	"flag"
	"log"

	config "github.com/ilhamfi27/ddd-golang-template/internal/config"
	appconfig "github.com/ilhamfi27/ddd-golang-template/internal/config/app"
	"github.com/ilhamfi27/ddd-golang-template/internal/handlers"
	_ "github.com/ilhamfi27/ddd-golang-template/swagger" // swagger is generated by Swag CLI, you have to import it.
)

// @title		Example
// @version		1.0.0
// @description		This is a simple API Example.
// @contact.name	Ilham
// @contact.url		https://nashul.com
// @contact.email	support@nashul.com
// @license.name	Apache 2.0
// @license.url		http://www.apache.org/licenses/LICENSE-2.0.html
func main() {
	// Load the environment variables
	appconfig.LoadEnv()

	// Initialize tracing
	env := appconfig.GetEnvVars()
	shutdown, err := config.InitTracing(env.ServiceName, env.JaegerEndpoint)
	if err != nil {
		log.Fatalf("Failed to initialize tracing: %v", err)
	}
	defer func() {
		if err := shutdown(context.Background()); err != nil {
			log.Printf("Failed to shutdown tracer: %v", err)
		}
	}()

	// Define the --migrate flag as a boolean
	migrate := flag.Bool("migrate", false, "Run database migrations")

	// Parse the command-line flags
	flag.Parse()

	h := handlers.NewHandler()

	if *migrate {
		h.Migrate()
	} else {
		h.Start()
	}
}
